# Generated by Django 4.1.3 on 2022-11-28 00:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Poll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('description', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Voter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('identifier', models.CharField(max_length=15, verbose_name='Matric No.')),
                ('photo', models.ImageField(null=True, upload_to='', verbose_name='Picture')),
            ],
        ),
        migrations.CreateModel(
            name='Nominee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('nickname', models.CharField(max_length=100)),
                ('photo', models.ImageField(upload_to='')),
                ('level', models.IntegerField(choices=[(1, '100'), (2, '200'), (3, '300'), (4, '400'), (5, '500')])),
                ('poll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nominees', to='vote.poll')),
            ],
        ),
    ]
