# Generated by Django 4.1.3 on 2022-11-28 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='nominee',
            name='votes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='voter',
            name='has_voted',
            field=models.BooleanField(default=False),
        ),
    ]
